galaxy_info:
  author: Ryan Kraus
  description: Hadoop Cluster
  license: Apache v2.0
  min_ansible_version: 1.2
  platforms:
    - name: RedHat
      versions:
      - 7
  galaxy_tags: [hadoop]
dependencies: []
